"""UI-independent Deadball game state and rules engine package."""

from .game_data import (
    GameDataError,
    GeneratedGame,
    GeneratorGameContext,
    adapt_generator_game,
    build_generator_game,
    load_generated_game,
)
from .dice import FixedDice, RandomDice
from .events import (
    ActionResult,
    BuntDiceRecord,
    DiceRecord,
    HitAndRunDiceRecord,
    PlayEvent,
    RuleTraceEntry,
    RunnerMove,
    StealDiceRecord,
    StealEvent,
    SubstitutionEvent,
)
from .manager import (
    ManagerDecision,
    ManagerError,
    ManagerOpportunity,
    ManagerState,
    decide_opportunity,
    generate_manager_daring,
    offensive_opportunity,
    pitching_opportunity,
    resolve_daring,
    select_replacement_pitcher,
)
from .rules import (
    legal_actions,
    resolve_bunt,
    resolve_defense_roll,
    resolve_hit_and_run,
    resolve_hit_table,
    resolve_steal,
    resolve_swing,
)
from .pitching import apply_pitcher_progress, step_pitch_die
from .substitutions import (
    SubstitutionError,
    defensive_substitution,
    effective_defensive_traits,
    pinch_hit,
    pinch_run,
    pitching_change,
    switch_defensive_positions,
    validate_team_state,
)
from .state import (
    DefensiveAssignment,
    GameResult,
    GameState,
    InitialGameState,
    InitialTeamState,
    PitchDieAdjustment,
    PitcherState,
    initialize_game,
)

__version__ = "0.1.0"

__all__ = [
    "GameDataError",
    "DefensiveAssignment",
    "DiceRecord",
    "GameResult",
    "GameState",
    "GeneratedGame",
    "GeneratorGameContext",
    "InitialGameState",
    "InitialTeamState",
    "ManagerDecision",
    "ManagerError",
    "ManagerOpportunity",
    "ManagerState",
    "PitchDieAdjustment",
    "PitcherState",
    "PlayEvent",
    "ActionResult",
    "BuntDiceRecord",
    "FixedDice",
    "HitAndRunDiceRecord",
    "RandomDice",
    "RunnerMove",
    "RuleTraceEntry",
    "StealDiceRecord",
    "StealEvent",
    "SubstitutionError",
    "SubstitutionEvent",
    "adapt_generator_game",
    "build_generator_game",
    "apply_pitcher_progress",
    "defensive_substitution",
    "decide_opportunity",
    "effective_defensive_traits",
    "generate_manager_daring",
    "initialize_game",
    "legal_actions",
    "load_generated_game",
    "offensive_opportunity",
    "pinch_hit",
    "pinch_run",
    "pitching_change",
    "pitching_opportunity",
    "resolve_bunt",
    "resolve_daring",
    "resolve_defense_roll",
    "resolve_hit_and_run",
    "resolve_hit_table",
    "resolve_steal",
    "resolve_swing",
    "select_replacement_pitcher",
    "step_pitch_die",
    "switch_defensive_positions",
    "validate_team_state",
]
